server:
  port: 8080

spring:
  profiles:
    include:
      - ENV
mvc:
  view:
    prefix: classpath:/templates/
    suffix: .html
  pathmatch:
    matching-strategy: ant_path_matcher
datasource:
  driver-class-name: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}

jwt:
  secret:${jwt.secret}
